[general]
default_gif = "/default.gif"
color = "FFFFFF"
led = "FFFFFF"

[busy]
emoji = "🔥"
id = "1231"
gif = "/busy.gif"
text = "Busy"
color = "F22F07"
led = "F22F07"

[coffee]
emoji = "☕"
id = "1232"
gif = "/coffee.gif"
text = "Coffee"
color = "723B04"
led = "723B04"

[focus]
emoji = "🎯"
id = "1233"
gif = "/focus.gif"
text = "Focus"
color = "074DF2"
led = "074DF2"

[call]
emoji = "📞"
id = "1234"
gif = "/call.gif"
text = "On call"
color = "8807F2"
led = "8807F2"

[lunch]
emoji = "🍽️"
id = "1235"
gif = "/lunch.gif"
text = "Lunch time"
color = "FF9100"
led = "FF9100"
